JECT-Study/JECT-Official-WebSite-Client

.gitignore
.prettierrc
eslint.config.js
index.html
package-lock.json
package.json
src/App.tsx
src/index.css
src/main.tsx
src/vite-env.d.ts
tsconfig.app.json
tsconfig.json
tsconfig.node.json
vite.config.ts

vite 프로젝트 생성하면서 기본적으로 설치된 모듈 외에 설치한 모듈은 다음과 같습니다. 
```ts
"tailwindcss": "^4.0.0", 
"prettier": "^3.4.2", // 일관성 있는 코드 스타일 유지
"prettier-plugin-tailwindcss": "^0.6.10", // 파일 저장 시 tailwind css 속성 자동 정렬 
"eslint-config-prettier": "^10.0.1", // eslint와 prettier 충돌 시 prettier 규칙이 우선
```
자주 사용되는 prettier 설정으로 세팅해두었습니다
변경하고 싶으신 부분이나 추가로 설정해야 할 부분이 있다면 말씀해주세요!
```ts
// .prettierrc 파일
{
"plugins": ["prettier-plugin-tailwindcss"],
"printWidth": 100, // 한 줄의 최대 길이를 100자로 제한
"tabWidth": 2, // 들여쓰기 크기를 2칸으로 설정
"trailingComma": "all", // 모든 곳에서 마지막 요소 뒤에 쉼표 추가
"singleQuote": true, // 문자열에 작은 따옴표(') 사용
"jsxSingleQuote": true, // JSX에서 작은 따옴표(') 사용
"arrowParens": "avoid", // 화살표 함수 매개변수가 하나일 때 () 감싸지 않음.
"semi": false // 세미콜론을 사용하지 않음
}
```
vscode의 [Tailwind CSS …

feat: 프로젝트 개발 환경 세팅

---

.storybook/preview.ts
src/components/common/Badge.stories.tsx
src/components/common/Badge.tsx
src/components/common/Interaction.stories.tsx
src/components/common/Interaction.tsx
src/components/common/Label.stories.tsx
src/components/common/Label.tsx
src/styles/interactionStyle.ts
src/styles/tokens/typography.css

이전 인터렉션에서 자식요소의 배경색 존재 여부를 고려하지 않고 구현하여 
배경색이 없을 경우 인터렉션의 투명도 값이 제대로 계산되지 않는 문제가 있어 해결하였습니다. 
```ts
interface InteractionProps {
children: React.ReactNode;
variant: Variant;
density: Density;
childHasBg: boolean; // 추가
childRadius?: Radius; // radius -> childRadius로 이름 변경
}
```
- Props로 `childHasBg` 가 추가되었습니다. 
- 기존 `radius` 에서 `childRadius` 로 이름이 변경되었습니다.
배경색이 있을 경우, 자식요소의 opacity를 조절하지만
배경색이 없을 경우, 인터렉션의 raga 값을 조절합니다. 
(opacity 대신 raba로 사용한 이유는 opacity로 할 경우 자식요소에도 함께 적용되어 텍스트가 안보입니다.)
🚨 **추가로, Interaction의 `focus-visible` 효과가 적용되기 위해서 
자식요소는 기본 블록 태그가 아닌 상호작용이 가능한 태그여야합니다.**  
ex) button, input, a, textarea, select ..
Label에 들어가는 텍스트를 `text` Prop에서 children 으로 수정되었습니다!
이렇게 하면 Label을 사용하는 컴포넌트에서 좀 더 텍스트에 대해 가독성이 좋다 생각하여 변경했습니다. 
++) Badge도 text prop에서 children으로 변경되었습니다 
스토리북 배경색 기본값을 …

fix: 인터렉션 컴포넌트 수정 및 storybook 설정 

---

src/components/common/Label.tsx
src/components/common/Title.stories.tsx
src/components/common/Title.tsx
src/components/common/callout/CalloutInformation.stories.tsx
src/components/common/callout/CalloutInformation.tsx
src/components/common/callout/CalloutNumerical.stories.tsx
src/components/common/callout/CalloutNumerical.tsx
src/components/common/callout/Hero.stories.tsx
src/components/common/callout/Hero.tsx
src/components/common/callout/HeroIndex.stories.tsx
src/components/common/callout/HeroIndex.tsx
src/styles/labelStyle.ts
src/styles/titleStyle.ts
src/styles/tokens/scheme.css

Title, Callout, Hero 컴포넌트를 구현했습니다. 
컴포넌트 수는 5가지지만 간단한 구조라서 구현도 간단하게 진행했습니다!
자세한 props 내용은 스토리북 확인해주시면 될 것 같습니다ㅎㅎ
구현을 하다가 tailwind와 동일한 이름을 사용하는 radius가 오버라이딩이 되지 않는 걸 발견했습니다.
css 변수명 자체를 그냥 tailwind의 네임스페이스와 다르게 수정해서 해결했습니다. 
@utility 에 정의한 `radius-*` 형태는 건들지 않아서 기존 형식 그대로 사용해도 문제 없습니다!
PR을 연달아 계속 올리고 있는데 스프린트가 곧 끝나서 조금 달리겠습니다..! 💪🙏🙌 
컴포넌트 폴더가 스토리북도 같이 작성하다보니까 금방 많아졌는데 
스토리북은 따로 폴더 만들어서 분리하는게 좋을 것 같단 생각이 살짝 드는데 원준님 의견은 어떠신지 궁금합니다ㅎㅎ
그리고 혹시 preview에 autodocs 추가하신다고 하셨는데 추가하게되면 스토리북 개별 파일에는 생략해도 되는건가요?
closes #19

feat: Title, Callout, Hero 컴포넌트 구현 

---

src/components/common/tab/Tab.stories.tsx
src/components/common/tab/Tab.tsx
src/components/common/tab/Tab.types.ts

처음 구현했던 구조를 한번 갈아엎는 과정에서.... 약간의 시간이 소요되었습니다! 😂 
- 전체 Tab 의 경우에는 Tab 컴포넌트를 props로 가지는 것이 아닌 children의 속성을 `TabItem` 으로 좁혀서 선언하였습니다.
- 필요에 따라서 기본 선택 속성인 `defaultActiveTabId` 을 옵셔널로 선언하였고, 해당 props이 없다면 첫번째 TabItem으로 선택되도록 처리했습니다.
```typescript
const tabItems = Array.isArray(children) ? children : [children];
```
는 children이 하나 일 때의 경우를 상정한 것입니다.
`TabItems`의 isActive와 onClick의 경우 부모인 Tab에서 TabItem에게 해당 값을 직접 주입하여 사용합니다.
다시 말해, Tab 내부에 TabItems의 경우 해당 props이 의존적이며, 독립적으로 사용될 경우 자체적인 props이 됩니다.
- 추가 발견한 문제 : 디자인에서와 실제 적용되는 typo의 미세한 차이로 인해, 스토리북에서 Tab Header의 끝부분이 미세하게 비어있는 문제가 발생하였습니다. 해당 부분을 이슈로 남겨놓을지, 해당 부분까지 수정을 해야할지 고민되네요.
(02.15 추가됨)
- Context API 방식을 활용해, Tab 컴포넌트는 string 형태의 id를 이용하여 Tab Header 부분과 해당 항목에 속하는 내용물인 Tab Panel을 조작할 수 있도록 수정했습니다.
- 실질적으로 사용하는 Tab 컴포넌트의 인터페이스는 …

feat: 탭 컴포넌트 구현

---

src/components/common/select/Select.stories.tsx
src/components/common/select/Select.tsx
src/components/common/tab/Tab.tsx

- Select의 경우 복잡한 구조를 가지고 있거나, 추가적인 렌더링 처리가 불필요해 보여 Tab의 경우와는 다르게 Compound Component Pattern은 사용하지 않았습니다.
- SelectItem의 children의 경우 clicked 되었을 때 우측에 오는 Icon 컴포넌트가 오는 공간입니다. 확장성 있는 방식을 위해 `children?: ReactNode;` 처리를 하였습니다.
- 실제로 컴포넌트에서 사용하는 인터페이스만 interface 형태를 사용하였고, 내부적인 요소들은 type으로 선언했습니다.
- `handleItemClick` 에서 이미 선택된 항목을 다시 클릭 시 클릭이 해제되도록 처리했습니다. 또한 onChange 콜백이 존재한다면 이를 이후 호출합니다. 
Interaction에 duration과 motion 주입 시 
```typescript
<Interaction
variant='default'
density='normal'
isInversed={false}
className='peer-hover:duration-faster peer-hover:ease-(--motion-fluent)'
>
```
로 표현되는데, 적용은 잘 되는거 같네요. 이러한 방식이 합당한지 궁금합니다.
closes #28

feat: Select 컴포넌트 구현

---

src/components/common/button/BlockButton.stories.tsx
src/components/common/button/BlockButton.tsx
src/components/common/button/LabelButton.stories.tsx
src/components/common/button/LabelButton.tsx
src/components/common/snackbar/SnackBar.stories.tsx
src/components/common/snackbar/SnackBar.tsx
src/styles/blockButtonStyle.ts
src/styles/labelButtonStyle.ts

- 단순한 컴포넌트이고, 시각적인 변주가 필요하지 않을 것이라고 판단이 되어 인터페이스 선언 시 `ComponentPropsWithoutRef<'div'>` 와 같은 추가적인 속성 주입을 하지 않고 단순 props만 이용해 선언하였습니다.
- 만약 항상 이 컴포넌트의 버튼 클릭 시 이벤트가 발생한다면 `onAction` 을 옵셔널에서 필수 props로 선언하는 것이 옳다고 생각되나, 일단 옵셔널(?) 처리를 하였습니다.
- 사용 시, 상위 div에서 width 제어가 필요합니다. (SnackBarStory 참고)
- #35 에서 처리된 Interaction 내부 props 변경점을 LabelButton과 BlockButton에 반영하였습니다.
- **isInversed** 의 경우에는 label(block)ButtonInteractionMap에 매개변수를 추가하여 처리하였습니다.
- disabled는 <button>의 기본 props로 별도로 props에는 선언하지 않았습니다.
- disabled 시 스타일을 clsx로 묶을 때, 후순위에 선언하여 오버라이딩을 의도하였지만, 반영이되지 않아 label(block)ButtonStyle 스타일 객체에 disabled 로 분기를 주어 스타일을 처리하였습니다.
- 또한, 컴포넌트 내부 combinedClasses 선언 시 disabled 유무에 따라 커서 이벤트 처리를 분기하였습니다.
```typescript
{
'cursor-not-allowed pointer-events-none': disabled,
'cursor-pointer …
```

feat: SnackBar 컴포넌트 구현

---

src/components/common/callout/HeroIndex.stories.tsx
src/components/common/callout/HeroIndex.tsx

HeroIndex props에 Badge 의 배경색 및 폰트색을 주입할 수 있도록 `badgeBgColor`, `badgeTextColor` 를 추가하였습니다. 
```ts
// 기본값
badgeBgColor = 'bg-fill-assistive-dark',
badgeTextColor = 'text-object-normal-dark',
```
HeroIndex 의 padding값이나 content를 children으로 변경하는 부분은 #78 에서 수정되어 건들지 않았습니다! (머지 충돌 방지)
closes #79

fix: HeroIndex 컴포넌트 수정

---

src/pages/Activity.tsx
src/router.tsx

활동 페이지 UI는 간단한 편이고 Card 컴포넌트가 사용됩니다 
데이터 배열은 임시로 노션 API 명세서에 있는 예시 데이터를 이용했는데 API 연동하면서 대체될 예정입니다!
API 명세서에 나와있는 임시 데이터에 id,label, content 와 같은 내용은 따로 없어서 백엔드 팀원분과 논의해봐야 할 것 같습니다
스크린샷에서는 링크 이동되는 과정 캡처가 불가능해서 안보이지만 링크 이동 잘 동작하는 것도 확인했습니다!
closes #43

feat: 활동 페이지 UI 구현

---

src/components/common/accordion/Accordion.tsx
src/components/common/button/LabelButton.tsx
src/styles/interaction.css

(해결방법이 시원치 않지만)
focus-visible 효과 발생 시 border이 덮어씌워지는 경우
그리고 overflow hidden 으로 인해 인터렉션 focus outline이 제대로 보이지 않던 문제를 해결했습니다. 
기존에 `focus-visible:before:shadow-focus-visible` 를 `focus-visible:shadow-focus-visible` 로 변경했습니다.
focus-visible 시 나타나는 하늘색 라인은 가상요소가 아닌 선택된 요소에 직접 나타납니다. 
이로써 위 2가지 문제를 해결할 수 있었습니다. 
카드 컴포넌트 
임의로 border이 들어간 박스
하지만 이렇게 변경할 경우 scale을 준 아코디언과 레이블 버튼에는 확장한 크기만큼 아웃라인이 나타나지 않는 문제가 발생합니다. 
그래서 scale을 위해 기존 인터렉션 스타일도 (스타일 네임에 `-sclae` 붙여서 ) 남기는 쪽으로 해결했습니다
생각했던 다른 방법
- 가상요소에 border를 inherit하는 방법 => 실패
- border-width 값 inherit이 제대로 동작 못함 
- 인라인으로 생기는 border의 특성 때문에 border가 2배로 들어가 요소의 크기가 작아져보임,
- scale 스타일을 가지고 있다면 focus-visible 코드를 동적 할당? 
- css 파일에선 불가능
문제는 해결됐는데 이렇게 하면 interaction.css 파일 코드 양이 2배가 되어서,, 🥺 
여러 방법을 생각해보았는데 이 방법이 최선인 것 같습니다..
조금이라도 중복되는 코드를 줄이기 위해서 유틸리티 …

fix: 인터렉션 focus-visible 효과 나타날 때 border가 보이지 않는 버그 해결

---

src/components/common/button/BlockButton.stories.tsx
src/components/common/button/BlockButton.tsx
src/components/common/button/LabelButton.stories.tsx
src/components/common/file/File.stories.tsx
src/components/common/snackbar/SnackBar.stories.tsx
src/components/common/tab/Tab.stories.tsx
src/components/common/tab/Tab.tsx
src/pages/ApplyApplicationInfo.tsx

(npm run build 실행 결과)
```typescript
export interface BlockButtonProps extends Omit<ComponentPropsWithoutRef<'button'>, 'style'> {
children: ReactNode;
leftIcon?: ReactNode;
rightIcon?: ReactNode;
size: Size;
style: Style;
hierarchy: Hierarchy;
}
```
에서 기존에는 단순히 `<ComponentPropsWithoutRef<'button'>` 만 사용하였는데, 이럴 경우 button의 기본 속성 style과 재정의한 style의 구분이 불분명하여 발생하는 이슈가 있었습니다.
Omit을 통해 원본 style을 제거하고 커스텀 style을 사용하는 방식으로 해결하였습니다.
구현하셨던 file 컴포넌트(common/file)의 타입 파일은
```typescript
export interface FileUrl {
id: string;
name: string;
url: string;
size: number;
}
```
이렇게 id 값이 string으로 처리되어있습니다. CDN url 관련해서 이러한 처리가 되어있는 걸로 알고 있는데, 스토리 파일에서 해당 id의 타입을 number에서 string으로 변경하였습니다.
#81 #82 에서 공유 드렸던 사용하지 않는 setIsReady 변수가 lint에서 에러로 인지합니다. 
주석 처리를 하기 보단, `const [isReady] = useState(false);` 이렇게 …

bug: 빌드 파일 생성 과정에서 발생한 에러 수정

---

src/apis/miniStudy.ts
src/utils/httpClient.ts

#101 이슈에서 설명했듯 requestHandler에서 요청과 응답의 제네릭 타입을 별도로 지정해줄 수 있도록 수정했습니다. 
payload 타입은 생략할 경우 undefiend로 지정됩니다. 
또한, api fetch 함수를 적을 때 응답 타입으로 `ApiResponse<T>` 를 중복적으로 작성하는 것을 피하기 위해 
requestHandler 내부에서 감싸주도록 수정했습니다.
closes #101

refactor: requestHandler 제네릭 타입 수정

---

src/components/common/checkbox/CheckBox.stories.tsx
src/components/common/checkbox/CheckBox.tsx
src/components/common/checkbox/CheckBox.types.ts
src/components/common/checkbox/CheckBoxIcon.tsx
src/components/common/icon/Icon.tsx
src/styles/interaction.css

- CheckBox의 상태(checked, isIndeterminate)에 따라  랜더링되는 Icon 컴포넌트를 분기합니다.
- 기본적으로 랜더링 하는 svg를 분기하는 쪽이 더 적절하다고 생각했지만, 공통적으로 사용하는 Icon 컴포넌트를 사용했습니다.
기본적으로 input 요소의 기본 props를 활용했습니다.
```typescript
| { isIndeterminate?: false; checked: true }
| { isIndeterminate: true; checked?: false }
| { isIndeterminate?: false; checked?: false }
);
```
해당 부분은 **체크박스의 상태를 세 가지 경우로 제한**하기 위한 유니온 타입입니다.
1. 체크박스가 checked 된 상태
2. 체크 박스가 indeterminate인 상태
3. 체크박스가 선택되지 않은 상태(inderminated 되지 않고, checked 되지 않음)
해당 유니온 타입을 통해 세 가지 경우로 제한함으로써, 체크박스가 동시에 indeterminate와 checked 상태가 되는 조합을 방지합니다.
- id props는 해당 `<input>` 의 식별자입니다. >> 여러 체크 박스가 있어도 id 값을 통해 구분가
- `<input>` 요소에 id를 부여하고, <Label> 컴포넌트에는 이 id를 htmlFor 속성으로 전달합니다.
- 순수 컴포넌트로 활용하기 위해 컴포넌트 내부에서는 상태관리를 하지 않습니다.
(3/09 추가)
- 체크 박스의 경우 Interaction을 가지는 실제 요소 …

feat: CheckBox 컴포넌트 구현

---

src/components/common/select/Select.stories.tsx
src/components/common/tab/Tab.stories.tsx
src/components/main/animatedSection/AnimatedSection.tsx
src/components/main/role/RoleBadge.tsx
src/components/main/role/RoleHero.stories.tsx
src/constants/faqPageData.tsx
src/constants/footer.ts
src/constants/mainPageData.tsx

전체 코드에서 사용된 직군명 `프로젝트 매니저`를 `프로덕트 매니저`로 변경했습니다.
푸터와 faq에서 사용되고 있던 `jectofficial@gmail.com` 이메일을 `jectofficial@ject.kr` 로 변경했습니다. 
메인 페이지의 데브옵스 애니메이션을 PM의 요청에 따라 비활성화 처리했습니다.
closes #103

refactor: 직군명, 이메일 변경 및 데브옵스 애니메이션 비활성화

---

src/components/apply/ApplySnackBar.tsx
src/components/common/snackbar/SnackBar.tsx
src/constants/applyMessages.tsx
src/pages/Activity.tsx
src/pages/Faq.tsx
src/pages/Main.tsx
src/pages/Project.tsx
src/pages/ProjectDetail.tsx

- 지원 스낵바의 경우 5개의 페이지에 들어가기 때문에 공통 컴포넌트로 분리 `ApplySnackBar`
- 메인 페이지만 스낵바의 문구가 달라 `message` props로 받습니다. 
- `width` props를 통해 스낵바의 너비가 달라집니다.
closes #119

feat: 페이지 하단 지원 스낵바 구현

---

src/components/common/file/FileItem.tsx
src/pages/ApplyRegistration.tsx
src/utils/draftUtils.ts

15분 간격으로 서버에 저장되는 임시저장 외 1분 간격으로 로컬 스토리지에 자동 임시 저장합니다. 
임시저장 플로우는 이렇게 진행됩니다. 
1. 지원서 작성 페이지 접근 전 로컬 스토리지 혹은 서버에 저장된 임시저장데이터가 있는지 확인 
2. 임시저장 불러오기는 로컬 스토리지 -> 서버 순으로 데이터를 가져옴. (로컬스토리지에 없다면 서버 값으로 업데이트)
3. 1분 간격으로 로컬 스토리지에 임시 저장
4. 15분 간격으로 서버로 임시 저장 요청 + 로컬 스토리에 임시 저장 
5. 직군 변경 시 로컬 스토리지 임시 저장 데이터 삭제
6. 제출 시 로컬 스토리지 데이터 삭제
로컬 스토리지가 서버에 있는 데이터보다 최신 데이터이기 때문에 먼저 가져옵니다. 
서버에 저장될 때 로컬 스토리지도 같이 저장시키는 이유는 서버가 로컬 스토리지보다 최신 데이터가 되지 않도록하기 위함입니다. 
업로드된 파일을 새로운 탭으로 열리지 않는 버그를 발견했습니다. 
FileItem 컴포넌트의 `openFile` 함수의 얼리 리턴 조건문을 수정해 해결했습니다.
closes #121

feat: 로컬스토리지 자동 임시 저장 기능 구현

---

.github/workflows/storybook.yml

와 [github-actions 업데이트](https://github.com/actions/runner-images/issues/11101)에 따라 
```yml
...
jobs:
storybook:
runs-on: ubuntu-20.04
...
```
로 처리된 `ubuntu-20.04` 버전은 deprecated 되었습니다.
`ubuntu-latest` 와 고민이 되었는데, 명시적으로 Ubuntu 22.04 LTS를 지정해주는 편이 안정적이라는 생각이 들어 22.04 버전으로 runner 버전을 업데이트 해주었습니다.
해당 PR의 하단 부분에서 작동되는 것을 확인하였습니다!
closes #132

bug: workflow runner 버전 업데이트

---

src/components/apply/Answers.tsx
src/components/apply/FileField.tsx
src/components/apply/SelectField.tsx
src/components/apply/UrlField.tsx
src/components/apply/selectBox.tsx
src/components/apply/textField.tsx
src/hooks/useCloseOutside.ts
src/types/apis/question.ts
src/utils/validateAnswersPayload.ts

SelectField 컴포넌트를 구현했습니다. 
업데이트된 지원서 문항 api를 바탕으로 문항의 `inputType`이 `SELECT` 타입일 경우 SelectField 컴포넌트를 그립니다.
아래 사항으로 업데이트 되었고 변경된 타입에 맞춰 수정했습니다!
- `label`, `selectOptions`, `maxFileSize` 추가
- `maxLength` -> `maxTextLength` 변경
- `inputType`에 `SELECT` 추가
셀렉트 필드에서 선택창을 연속 클릭하면 select가 닫혔다가 다시 열리는 깜빡임 현상이 있었습니다. 
이 문제를 해결하기 위해 useCloseOutside 훅에 outSide 범위 기준을 판단하는 ref를 여러 개 받을 수 있도록 수정했습니다. 
ref를 배열로 넘겨줄 수도 있고 여전히 ref 하나만 단독으로도 넘길 수 있어 이전 useCloseOutside를 사용하고 있던 부분에 영향은 없습니다.
closes #123

feat: 답변 SELECT 필드 추가 

---

src/components/common/accordion/Accordion.stories.tsx
src/components/common/accordion/Accordion.tsx
src/constants/faqPageData.tsx
src/hooks/useFaqNavigation.ts
src/pages/ApplyVerifyEmail.tsx
src/pages/Faq.tsx
src/router.tsx

- 전반적인 컴포넌트 내 개선이 있었으며, 기본적인 틀은 `Select` 컴포넌트의 구조와 유사하게 조정하였습니다.
- 실제 사용되는 컴포넌트는 기존과 그대로 `Accordion` 이며, 기존에 단일한 `Accordion`(열고 닫는 하나의 요소)는 `AccordionItem` 으로 선언하였습니다. (이러한 처리로 인해 기존에 Accordion 자체를 mapping 하는 방식에서 Accordion 내부의 상태 변경으로 열고 닫음을 수행합니다. == 다수의 열고 닫는 요소들이 모인 것이 하나의 `Accordion`)
```typescript
<TabPanel id={1}>
<div className='mt-(--gap-4xl)'>
<Accordion
items={getActiveFaqData()}
defaultOpenId={openAccordionId}
onChange={handleAccordionChange}
/>
</div>
</TabPanel>
```
와 같이 하나의 `TabPanel` 안에 하나의 `Accordion` 이 들어갑니다. (스토리북을 참고해주세요!)
- 옵셔널 파라미터 방식을 이용해서
```typescript
{ path: `${PATH.faq}/:tabId?/:questionId?`, element: <Faq /> }
```
와 같이 url 자체에 탭 ID와 해당 탭 중 출력하는 Accordion의 ID를 알 수 있도록 설정하였습니다.
- react-router-dom의 `useParams` 를 이용하기 때문에 url에서 감지하는 `tabId` 와 `questionId` 는 string …

feat: FAQ 페이지 기능 변경 및 개선

---

src/apis/apply.ts
src/constants/apiEndpoint.ts
src/hooks/useResetPinMutation.ts
src/pages/ApplyVerifyEmail.tsx
src/pages/ApplyVerifyPin.tsx
src/types/apis/apply.ts

#134 에서 요청하셨던 버튼의 문구을 요구사항에 맞게 수정하였습니다.
```typescript
<BlockButton
type='submit'
form={isResetPin ? 'resetPinForm' : 'registerForm'}
disabled={isSubmitButtonDisabled}
size='lg'
style='solid'
hierarchy='accent'
rightIcon={
!isResetPin && <Icon name='forward' size='md' fillColor={rightIconFillColor} />
}
>
{isResetPin ? 'PIN 다시 설정 완료하기' : '다음 단계로 진행하기'}
</BlockButton>
```
와 같이 `isResetPin` 값에 따라 관리하는 `<form>` 이 변경되며, label도 이에 맞춰서 변경됩니다.
(ApplyVerifyEmail의 213 line~ 233 line에서) **resetPinMutate 성공** 시 
```typescript
onSuccess: response => {
if (response.status === 'SUCCESS') {
addToast('PIN을 다시 설정했어요', 'positive');
setStep(1);
setStoredEmail('');
setIsAuthCodeExpired(false);
setVerificationToken(null);
resetEmailForm();
resetVerificationForm();
resetPinForm();
}
},
```
와 같이 PIN 재설정 flow에서 …

feat: PIN 재설정 기능 구현

---

src/apis/apply.ts
src/hooks/useRegisterMemberMutation.ts
src/pages/ApplyVerifyEmail.tsx
src/types/apis/apply.ts

- useRegisterMemberMutation 에서 기존 로직으로 로컬에서 직접 토큰을 header로 전달하는 로직을 제거하였습니다.
기존 임시회원가입 시 요구되는 `verficationToken`의 경우에도 서버에서 직접 쿠키에 있는 값을 읽어 권한을 부여하는 방식으로 변경된 점을 반영하였습니다.
closes #152

bug: 임시 회원가입 시 토큰 핸들링이 정상적으로 처리되지 않는 문제 해결

---

src/pages/ApplyVerifyEmail.tsx

- `const [verificationToken, setVerificationToken] = useState<string | null>(null);`
해당 상태는 더 이상 쓰지 않습니다. #152 에서 쿠키 관리를 서버에서 직접 처리하는 구조로 인한 변경점
```typescript
const onRegisterMemberSubmit = ({ pin }: RegisterMemberPayload) => {
if (!verificationToken) {
console.error('인증 토큰이 없습니다. 인증 단계를 다시 진행해주세요.');
return;
}
```
에서 처럼 인증 토큰이 없으면 return 해주는 로직을 제거합니다. 
closes #155

bug: 임시 회원가입 버튼 클릭 이벤트가 전송안되는 버그 해결

---

src/components/apply/Answers.tsx
src/components/apply/FileField.tsx
src/components/layout/Layout.tsx
src/components/layout/ScrollToTop.tsx
src/constants/applyMessages.tsx
src/constants/applyPageData.tsx
src/hooks/useDraftQuery.ts
src/pages/ApplyVerifyEmail.tsx
src/pages/ApplyVerifyPin.tsx

스크롤 최상단으로 이동할 때 `window.scrollTo()` 속성으로 behavior: 'smooth' 효과를 줄 수 있는데 현재는 줄 수 없을 것 같습니다.
메인 페이지에서 스크롤 기능이 잠깐 방지되는 로직이 있어 `메인페이지` -> 다른 페이지 혹은 다른 페이지 -> `메인 페이지` 일 때 최상단으로 이동되지 않기 때문입니다 그래서 지금은 부드러운 효과 없이 바로 최상단으로 순간이동합니다 
이 두 부분은 배포해봐야 확실히 해결되었는지 확인 가능합니다. 
#159

fix: 스크롤 최상단 이동 기능 추가, 지원서 임시 저장 조회 및 파일 업로드 버그 수정

---

src/hooks/useFaqNavigation.ts

- handleTabChange 함수에서 URL은 변경되지만 실제 탭 상태는 동기화되지 않는 문제가 발생하였습니다.
- { replace: true } 없이 navigate를 사용하면, 새로운 URL이 브라우저 히스토리 스택에 추가됩니다. 하지만 activeTabId(탭의 state)는 자동으로 업데이트되지 않습니다. 
- UseEffect로 activeTabId를 동기화 해주기 보다,
```typescript
if (tabId !== 1) {
void navigate(`${PATH.faq}/${tabId}`, { replace: true });
} else {
void navigate(`${PATH.faq}`, { replace: true });
}
};
```
와 같이 navigate 시에 `{replace: true}` 를 사용해 히스토리 스택에 새 항목을 추가하지 않도록 처리하였습니다.
https://github.com/user-attachments/assets/8fceca88-8bbf-4917-a168-9c7d1424eb43
closes #163

bug: Faq 페이지 내 탭 이동 시 히스토리가 유지되는 문제 해결

---

src/constants/dialog.tsx
src/hooks/useDirtyCheckDialog.ts
src/hooks/useLeaveConfirmDialog.ts
src/pages/ApplyRegistration.tsx
src/types/ui/dialog.ts

```ts
const useDirtyCheckDialog = (when: boolean) => {
const { openDialog } = useDialogActions();
const blocker = useBlocker(({ currentLocation, nextLocation }) => { 
return when && currentLocation.pathname !== nextLocation.pathname;
}); // props로 받은 when이 true 여야하며, 현재페이지 pathname, 이동할 페이지 pathname이 다를 때 `blocked` 상태로 반환
useEffect(() => {
if (blocker.state === 'blocked') {
openDialog({
type: 'dirtyCheck',
onPrimaryBtnClick: () => blocker.proceed(), // 다른 페이지 이동
onSecondaryBtnClick: () => blocker.reset(), // 현재 페이지 남음
});
}
}, [blocker, openDialog]);
};
```
react router의 `useBlocker` 를 사용하여 구현했습니다. 
공식 문서에서 설명하는 useBlocker 기능은 이렇습니다. 
> "이 기능은 SPA(단일 페이지 애플리케이션) 내에서의 페이지 이동을 차단하고, 사용자가 이동을 시도할 때 확인 다이얼로그를 띄워주는 기능을 허용합니다. 주로 입력 중인 폼 데이터가 손실되는 것을 방지하기 위해 사용됩니다. 단, 새로고침(hard reload)이나 외부 …

fix: 지원서 작성 페이지 벗어날 경우 다이얼로그 표시 

---

src/App.tsx
src/components/common/footer/Footer.tsx
src/components/common/navigation/Navigation.tsx
src/components/layout/PagesContainer.tsx
src/pages/TempMobile.tsx

보통 모바일 기기라고 판단하는 768px 기준으로 모바일 UI가 보여지도록 했습니다.
추가로 헤더에 UI 추가된 border 스타일과 푸터에 잘못들어가있던 색상 값을 변경했습니다.
closes #170

fix: 임시 모바일 UI 구현

---

src/apis/auth.ts
src/utils/interceptor.ts

```typescript
try {
const refreshResponse = await refreshAccessToken();
if (refreshResponse.status === 'SUCCESS' && refreshResponse.data) {
return instance(originalRequest);
}
```
에서  `refreshAccessToken()` 만 수행되고 이후 기존 요청 재요청이 수행되지 않는 문제를 발견했습니다.
(thanks to. 채연님)
```typescript
export const refreshAccessToken = async (): Promise<ApiResponse<RefreshTokenResponse>> => {
return await axios
.post<ApiResponse<RefreshTokenResponse>>(`${BASE_URL}${API_ENDPOINT.refreshToken}`)
.then(response => response.data);
};
```
에서 기본 axios 호출인데 쿠키 기반 인증에서 필수적으로 기입해야 하는 `withCredentials: true` 와 `Content-Type` Header 가 누락되어 있었습니다!!!
```typescirpt
export const refreshAccessToken = async (): Promise<ApiResponse<RefreshTokenResponse>> => {
return await axios …
```

bug: 토큰 재발급 후 기존 api 호출이 수행되지 않는 문제 해결

---

src/hooks/useMemberProfileInitialStatusQuery.ts
src/pages/ApplyVerifyPin.tsx
src/types/apis/apply.ts

최초 로그인이 아니라면 프로필 정보 등록 여부 없이 프로필 정보 입력 페이지를 넘어가는 문제 발생 
임시 회원 최초 프로필 등록 여부 `/members/profile/initial/status` api를 사용하여 
로그인 버튼 클릭 시 프로필 정보가 등록되어 있는지 확인
프로필 정보 등록 확인 => 지원서 제출 여부 확인 => 임시 지원서 여부 확인 => 임시 지원서 초기화 순으로 api를 호출합니다. 
프로필 정보가 등록되지 않았다면 `apply/application-info` 페이지 이동
지원서가 제출되어있다면 `apply/complete` 페이지로 이동
임시 지원서가 있다면 다이얼로그 띄우고 다이얼로그의 `이어서 작성하기` 버튼 클릭 시 `apply/registration` 페이 이동. 
임시 지원서가 없다면 `apply/registration` 페이지 이동. 
closes #186

Bug: 임시 회원 최초 프로필 등록 여부 확인 api 연결

---

package-lock.json
package.json
src/hooks/useRedirectMaintenance.ts

`date-fns-tz` 라이브러리를 선택한 이유는 다음과 같습니다. 
- 가벼운 크기 
- 타임존 처리만 필요한 경우이기 때문
```ts
const now = new Date();
const kstDate = toZonedTime(now, 'Asia/Seoul');
const nextTime = new Date(kstDate);
```
`toZonedTime` 메서드 사용하여 점검 시간을 계산하기 전에 한국을 기준으로 계산되도록 수정했습니다. 
이미 로컬 시간이 한국인 경우에도 잘 적용됨 확인하였습니다.
closes #196

refactor: 점검 시간 기준을 KST으로 수정

---

index.html
package-lock.json
package.json
src/main.tsx
vite-env.d.ts

(수동으로 트래킹 훅을 짜기 위해 feat 브랜치로 열었는데, 전역 설정 후 gtm 내부에서 설정을 추가하는 방향성으로 변경 되었습니다. chore 브랜치라고 생각해주셔도 좋아요!) 
- 현재 요구되는 지원 페이지, 랜딩 페이지에 대한 이벤트 트래킹은 단순 페이지 유입 경로 트래킹 용도로 사용될 예정입니다. 따라 context api나 [gtm 관련 라이브러리](https://www.npmjs.com/package/react-gtm-module) 를 사용하기 보다 index.html에 단순 주입후 **GTM 관리 화면에서 추가 설정을 제어하는 방향**으로 방향성을 선회하였습니다.
- 기존 index.html 에 스크립트 형태로 선언한 amplitude의 경우 amplitude 키가 직접 노출되어있는 문제가 있었습니다. 따라서 Main.tsx 에 gsap, sentry를 초기화한 것과 동일한 방식으로 Amplitude를 초기화하였습니다.
```typescript
amplitude.init(import.meta.env.VITE_AMPLITUDE_API_KEY, undefined, {
autocapture: { elementInteractions: true },
});
amplitude.add(sessionReplayPlugin({ sampleRate: 1 }));
```
undefined 위치에는 userId를 입력하는 부분인데, 저희 웹사이트 특성상 특정한 유저를 트래킹할 필요가 없기 때문에 해당 값은 undefined로 처리하였습니다. 이외의 설정은 기존 스크립트와 동일합니다.
- 스크립트 내부 gtm 설정 …

chore: gtm 이벤트 트래킹을 위한 전역 설정

---

index.html
public/naver3ccdef7b530e1d116875864d53670f69.html
public/robots.txt
public/sitemap.xml

네이버 서치 어드바이저에 사이트를 등록하고 소유 확인을 위한 html 문서를 추가했습니다. 
에러 페이지(점검 페이지 포함)와 어드민 페이지는 제외한 페이지에 접근하도록 설정했습니다.
사이트맵은 웹사이트의 구조를 검색 엔진과 사용자에게 알려주는 파일로, 웹사이트의 페이지를 검색 엔진이 쉽게 찾고 크롤링할 수 있도록 돕습니다. 네비게이션으로 접근할 수 있는 페이지로 설정해두었습니다. 
원래는 https://www.xml-sitemaps.com/ 사이트를 통해서 자동 생성하려고 했는데 해당 사이트에서 점검페이지만 크롤링하는 것 같아서 수동으로 작성해두었습니다..! 왜 점검페이지만 나오는지는 원인을 좀 더 알아봐야할 것 같습니다 🤔
기본적인 메타 태그들만 추가해두었습니다
title이 `JECT` -> `젝트` 로 수정되었습니다.
closes #148

chore: seo 개선 작업

---

src/App.tsx
src/constants/path.ts
src/pages/Activity.tsx
src/pages/Apply.tsx
src/pages/Faq.tsx
src/pages/Main.tsx
src/pages/Project.tsx
src/pages/ProjectDetail.tsx

메인 페이지, 프로젝트 목록 및 상세 페이지, 활동 페이지, faq 페이지에 있던 지원 스낵바를 제거했습니다. 
또한 지원 페이지에서 `젝트 3기 지원하기` 버튼을 비활성화했습니다.
버튼은 혹시 몰라 click 이벤트도 제거했습니다.
해당 코드는 5월 8일 오전 12:00에 배포 진행될 예정입니다!
closes #208

feat: 지원 마감 UI 처리

---

src/pages/Apply.tsx
src/pages/RecruitmentComplete.tsx
src/router.tsx

GNB의 `지원하기` 탭 클릭 시 RecruitmentComplete 컴포넌트 페이지로 이동됩니다. 
해당 페이지의 cta 버튼 클릭 시 4기 신청 알림을 신청하는 구글폼이 새탭으로 열립니다. 
closes #212

feat: 지원하기 페이지에서 모집 마감 페이지로 변경
